### ISSUE TITLE
Install Randomise.me Dependencies failed

### ISSUE THREAD

**Issue by drcjar** [openhealthcare/developer#25]
TASK: [projects | Install Randomise.me Dependencies] ************************** 
failed: [default] => {"changed": true, "cmd": ["/home/vagrant/.virtualenvs/rm/bin/pip", "install", "-r", "/usr/lib/ohc/randomise.me/requirements.txt"], "delta": "0:01:38.554970", "end": "2015-03-05 23:08:04.197239", "rc": 1, "start": "2015-03-05 23:06:25.642269"}
stdout: Downloading/unpacking Cython==0.19.1 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 1))
  Running setup.py egg_info for package Cython
    Compiling module Cython.Plex.Scanners ...
    Compiling module Cython.Plex.Actions ...
    Compiling module Cython.Compiler.Lexicon ...
    Compiling module Cython.Compiler.Scanning ...
    Compiling module Cython.Compiler.Parsing ...
    Compiling module Cython.Compiler.Visitor ...
    Compiling module Cython.Compiler.FlowControl ...
    Compiling module Cython.Compiler.Code ...
    Compiling module Cython.Runtime.refnanny ...
    
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Downloading/unpacking Django==1.5.1 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 2))
  Running setup.py egg_info for package Django
    
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking Jinja2==2.7 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 3))
  Running setup.py egg_info for package Jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking MarkupSafe==0.18 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 4))
  Downloading MarkupSafe-0.18.tar.gz
  Running setup.py egg_info for package MarkupSafe
    
Downloading/unpacking Pillow==2.0.0 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 5))
  Running setup.py egg_info for package Pillow
    
    warning: no previously-included files found matching '.hgignore'
    warning: no previously-included files found matching '.hgtags'
    warning: no previously-included files found matching 'BUILDME.bat'
    warning: no previously-included files found matching 'make-manifest.py'
    warning: no previously-included files found matching 'SHIP'
    warning: no previously-included files found matching 'SHIP.bat'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching 'README' under directory 'docs'
    warning: no files found matching 'CHANGES' under directory 'docs'
    warning: no files found matching 'CONTENTS' under directory 'docs'
Downloading/unpacking South==0.7.6 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 6))
  Running setup.py egg_info for package South
    
Downloading/unpacking Werkzeug==0.8.3 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 7))
  Running setup.py egg_info for package Werkzeug
    
    warning: no files found matching '*' under directory 'werkzeug/debug/templates'
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking amqp==1.0.11 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 8))
  Running setup.py egg_info for package amqp
    
Downloading/unpacking anyjson==0.3.3 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 9))
  Downloading anyjson-0.3.3.tar.gz
  Running setup.py egg_info for package anyjson
    
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/lib/python2.7 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 10))
Downloading/unpacking billiard==2.7.3.27 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 11))
  Running setup.py egg_info for package billiard
    
    warning: no files found matching '*.py' under directory 'Lib'
Downloading/unpacking celery==3.0.18 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 12))
  Running setup.py egg_info for package celery
    Upgrade: no old version found.
    
    no previously-included directories found matching '*.pyc'
Downloading/unpacking cssselect==0.8 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 13))
  Could not find any downloads that satisfy the requirement cssselect==0.8 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 13))
No distributions at all found for cssselect==0.8 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 13))
Storing complete log in /home/vagrant/.pip/pip.log

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/sam/vagrant.retry

default                    : ok=45   changed=29   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by davidmiller** [comment]
I don't really believe that there is no cssselect 0.8 because https://pypi.python.org/pypi/cssselect/0.8 

Do you get the same error if you re-run ?

**Comment by drcjar** [comment]
same error on re-run

**Comment by davidmiller** [comment]
I have updated the dependencies in the RM repo.
Re running should pull down the latest version and update the relevant requirements.

Longer term we might like to drop RM from the default install of this.

**Comment by drcjar** [comment]
Re-running vagrant provision results in the same error still.

**Comment by drcjar** [comment]
TASK: [projects | Install Randomise.me Dependencies] ************************** 
failed: [default] => {"changed": true, "cmd": ["/home/vagrant/.virtualenvs/rm/bin/pip", "install", "-r", "/usr/lib/ohc/randomise.me/requirements.txt"], "delta": "0:00:58.979130", "end": "2015-03-09 10:45:07.528031", "rc": 1, "start": "2015-03-09 10:44:08.548901"}
stdout: Downloading/unpacking Cython==0.19.1 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 1))
  Running setup.py egg_info for package Cython
    Compiling module Cython.Plex.Scanners ...
    Compiling module Cython.Plex.Actions ...
    Compiling module Cython.Compiler.Lexicon ...
    Compiling module Cython.Compiler.Scanning ...
    Compiling module Cython.Compiler.Parsing ...
    Compiling module Cython.Compiler.Visitor ...
    Compiling module Cython.Compiler.FlowControl ...
    Compiling module Cython.Compiler.Code ...
    Compiling module Cython.Runtime.refnanny ...
    
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Downloading/unpacking Django==1.5.1 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 2))
  Running setup.py egg_info for package Django
    
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking Jinja2==2.7 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 3))
  Running setup.py egg_info for package Jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking MarkupSafe==0.18 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 4))
  Downloading MarkupSafe-0.18.tar.gz
  Running setup.py egg_info for package MarkupSafe
    
Downloading/unpacking Pillow==2.0.0 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 5))
  Running setup.py egg_info for package Pillow
    
    warning: no previously-included files found matching '.hgignore'
    warning: no previously-included files found matching '.hgtags'
    warning: no previously-included files found matching 'BUILDME.bat'
    warning: no previously-included files found matching 'make-manifest.py'
    warning: no previously-included files found matching 'SHIP'
    warning: no previously-included files found matching 'SHIP.bat'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching 'README' under directory 'docs'
    warning: no files found matching 'CHANGES' under directory 'docs'
    warning: no files found matching 'CONTENTS' under directory 'docs'
Downloading/unpacking South==0.7.6 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 6))
  Running setup.py egg_info for package South
    
Downloading/unpacking Werkzeug==0.8.3 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 7))
  Running setup.py egg_info for package Werkzeug
    
    warning: no files found matching '*' under directory 'werkzeug/debug/templates'
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking amqp==1.0.11 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 8))
  Running setup.py egg_info for package amqp
    
Downloading/unpacking anyjson==0.3.3 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 9))
  Downloading anyjson-0.3.3.tar.gz
  Running setup.py egg_info for package anyjson
    
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/lib/python2.7 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 10))
Downloading/unpacking billiard==2.7.3.27 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 11))
  Running setup.py egg_info for package billiard
    
    warning: no files found matching '*.py' under directory 'Lib'
Downloading/unpacking celery==3.0.18 (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 12))
  Running setup.py egg_info for package celery
    Upgrade: no old version found.
    
    no previously-included directories found matching '*.pyc'
Downloading/unpacking cssselect (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 13))
  Could not find any downloads that satisfy the requirement cssselect (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 13))
No distributions at all found for cssselect (from -r /usr/lib/ohc/randomise.me/requirements.txt (line 13))
Storing complete log in /home/vagrant/.pip/pip.log

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/sam/vagrant.retry

default                    : ok=45   changed=29   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by rossjones** [comment]
Creating a new virtualenv, and downloading that specific version works for me.  There's definitely something weird going on.  Does this work for you?

```bash
cd /tmp
mkdir csstest; cd csstest
virtualenv .
. bin/activate
pip install cssselect==0.8
```

**Comment by drcjar** [comment]
that works

think I might just try starting over
